spring:
  application:
    name: budget

  main:
    allow-circular-references: true

  datasource:
    url: JDBC:mysql://localhost:3306/anembok
    username: anembok
    password: anembok
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: JDBC:mysql://localhost:3306/anembok
    user: anembok
    password: anembok
    driver-class-name: com.mysql.cj.jdbc.Driver
    connect-retries: 10
    connect-retries-interval: 10
    baseline-on-migrate: true

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none   # create, create-drop, validate, update
    show-sql: true
    open-in-view: false

server:
  port: 8086

logging:
  level:
    org.flywaydb: INFO
